// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SampleServerSide;

namespace SampleServerSide.Migrations
{
    [DbContext(typeof(BloggingContext))]
    partial class BloggingContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0-preview8.19405.11");

            modelBuilder.Entity("SampleServerSide.Blog", b =>
                {
                    b.Property<int>("BlogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Rating")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Url")
                        .HasColumnType("TEXT");

                    b.HasKey("BlogId");

                    b.ToTable("Blogs");

                    b.HasData(
                        new
                        {
                            BlogId = 1,
                            Rating = 5,
                            Url = "www.fakeblog.com"
                        },
                        new
                        {
                            BlogId = 2,
                            Rating = 4,
                            Url = "www.fakeblog2.com"
                        },
                        new
                        {
                            BlogId = 3,
                            Rating = 3,
                            Url = "www.fakeblog3.com"
                        });
                });

            modelBuilder.Entity("SampleServerSide.Post", b =>
                {
                    b.Property<int>("PostId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BlogId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DatePosted")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasMaxLength(25);

                    b.HasKey("PostId");

                    b.HasIndex("BlogId");

                    b.ToTable("Posts");

                    b.HasData(
                        new
                        {
                            PostId = 1,
                            BlogId = 1,
                            Content = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
                            DatePosted = new DateTime(2019, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Dummies Guide to Blazor"
                        },
                        new
                        {
                            PostId = 2,
                            BlogId = 1,
                            Content = "Donec non aliquet tortor, finibus gravida arcu. Donec ac eros eget tortor ultricies aliquam quis eget dolor. Proin vel enim sapien. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Aenean a sapien nulla. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam ultrices erat at tempor vulputate. Mauris nec lacus sit amet augue egestas consequat eget in nunc.",
                            DatePosted = new DateTime(2019, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The 9 Best Blazor Twitter Feeds to Follow"
                        },
                        new
                        {
                            PostId = 3,
                            BlogId = 1,
                            Content = "Nunc suscipit dolor id ipsum scelerisque, ac dictum sem hendrerit. Aliquam ornare libero in est mollis pretium. Maecenas convallis diam sollicitudin tortor molestie consequat. Nullam massa nibh, sagittis nec dictum sed, viverra vitae lacus. Sed lorem ante, ultrices eu rhoncus eu, lobortis sed magna. Donec rutrum libero iaculis tellus convallis placerat. Donec non magna fermentum, dapibus libero ullamcorper, tempor urna. Suspendisse a nunc ac lectus faucibus porttitor. Suspendisse condimentum iaculis lacinia. Vivamus interdum dictum rhoncus. Cras lacinia quam non est dignissim consectetur. Praesent eu purus vel tortor aliquet dictum sed ut leo. Integer accumsan quam ipsum, in scelerisque elit ultrices a. Maecenas vel molestie risus.",
                            DatePosted = new DateTime(2019, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "7 Facts About Blazor Everyone Thinks are True"
                        },
                        new
                        {
                            PostId = 4,
                            BlogId = 1,
                            Content = "Nam tincidunt dignissim elementum. Suspendisse condimentum nulla ut lectus pretium pharetra quis eget justo. In condimentum justo ac varius rutrum. Praesent et suscipit velit, non efficitur mauris. Donec cursus lorem eu dui sollicitudin, pharetra tristique massa accumsan. Curabitur et malesuada tellus. Fusce ac elementum elit, a condimentum eros.",
                            DatePosted = new DateTime(2019, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "18 Podcasts About Blazor"
                        },
                        new
                        {
                            PostId = 5,
                            BlogId = 1,
                            Content = "Fusce consectetur cursus scelerisque. Mauris vestibulum aliquet gravida. Pellentesque vitae elit lectus. Suspendisse tempor aliquam risus, nec faucibus massa tincidunt ut. Vestibulum dapibus ligula sollicitudin odio interdum placerat. Curabitur tempus malesuada mi, a dignissim quam suscipit et. Nunc eget ultricies tellus, sit amet ultrices libero. Donec sollicitudin porta viverra. Mauris ac ligula sit amet dolor tincidunt hendrerit in vitae nibh. Mauris non mi purus. Fusce non convallis est. Fusce ipsum justo, malesuada mollis tortor a, scelerisque iaculis justo.",
                            DatePosted = new DateTime(2019, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Why Blazor Will Change Your Life"
                        },
                        new
                        {
                            PostId = 6,
                            BlogId = 2,
                            Content = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
                            DatePosted = new DateTime(2019, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Dummies Guide to ASP.NET"
                        },
                        new
                        {
                            PostId = 7,
                            BlogId = 2,
                            Content = "Donec non aliquet tortor, finibus gravida arcu. Donec ac eros eget tortor ultricies aliquam quis eget dolor. Proin vel enim sapien. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Aenean a sapien nulla. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam ultrices erat at tempor vulputate. Mauris nec lacus sit amet augue egestas consequat eget in nunc.",
                            DatePosted = new DateTime(2019, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The 9 Best ASP.NET Twitter Feeds to Follow"
                        },
                        new
                        {
                            PostId = 8,
                            BlogId = 2,
                            Content = "Nunc suscipit dolor id ipsum scelerisque, ac dictum sem hendrerit. Aliquam ornare libero in est mollis pretium. Maecenas convallis diam sollicitudin tortor molestie consequat. Nullam massa nibh, sagittis nec dictum sed, viverra vitae lacus. Sed lorem ante, ultrices eu rhoncus eu, lobortis sed magna. Donec rutrum libero iaculis tellus convallis placerat. Donec non magna fermentum, dapibus libero ullamcorper, tempor urna. Suspendisse a nunc ac lectus faucibus porttitor. Suspendisse condimentum iaculis lacinia. Vivamus interdum dictum rhoncus. Cras lacinia quam non est dignissim consectetur. Praesent eu purus vel tortor aliquet dictum sed ut leo. Integer accumsan quam ipsum, in scelerisque elit ultrices a. Maecenas vel molestie risus.",
                            DatePosted = new DateTime(2019, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "7 Facts About ASP.NET Everyone Thinks are True"
                        },
                        new
                        {
                            PostId = 9,
                            BlogId = 2,
                            Content = "Nam tincidunt dignissim elementum. Suspendisse condimentum nulla ut lectus pretium pharetra quis eget justo. In condimentum justo ac varius rutrum. Praesent et suscipit velit, non efficitur mauris. Donec cursus lorem eu dui sollicitudin, pharetra tristique massa accumsan. Curabitur et malesuada tellus. Fusce ac elementum elit, a condimentum eros.",
                            DatePosted = new DateTime(2019, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "18 Podcasts About ASP.NET"
                        },
                        new
                        {
                            PostId = 10,
                            BlogId = 2,
                            Content = "Fusce consectetur cursus scelerisque. Mauris vestibulum aliquet gravida. Pellentesque vitae elit lectus. Suspendisse tempor aliquam risus, nec faucibus massa tincidunt ut. Vestibulum dapibus ligula sollicitudin odio interdum placerat. Curabitur tempus malesuada mi, a dignissim quam suscipit et. Nunc eget ultricies tellus, sit amet ultrices libero. Donec sollicitudin porta viverra. Mauris ac ligula sit amet dolor tincidunt hendrerit in vitae nibh. Mauris non mi purus. Fusce non convallis est. Fusce ipsum justo, malesuada mollis tortor a, scelerisque iaculis justo.",
                            DatePosted = new DateTime(2019, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Why ASP.NET Will Change Your Life"
                        },
                        new
                        {
                            PostId = 11,
                            BlogId = 3,
                            Content = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
                            DatePosted = new DateTime(2019, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Dummies Guide to Telerik UI"
                        },
                        new
                        {
                            PostId = 12,
                            BlogId = 3,
                            Content = "Donec non aliquet tortor, finibus gravida arcu. Donec ac eros eget tortor ultricies aliquam quis eget dolor. Proin vel enim sapien. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Aenean a sapien nulla. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam ultrices erat at tempor vulputate. Mauris nec lacus sit amet augue egestas consequat eget in nunc.",
                            DatePosted = new DateTime(2019, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The 9 Best Telerik UI Twitter Feeds to Follow"
                        },
                        new
                        {
                            PostId = 13,
                            BlogId = 3,
                            Content = "Nunc suscipit dolor id ipsum scelerisque, ac dictum sem hendrerit. Aliquam ornare libero in est mollis pretium. Maecenas convallis diam sollicitudin tortor molestie consequat. Nullam massa nibh, sagittis nec dictum sed, viverra vitae lacus. Sed lorem ante, ultrices eu rhoncus eu, lobortis sed magna. Donec rutrum libero iaculis tellus convallis placerat. Donec non magna fermentum, dapibus libero ullamcorper, tempor urna. Suspendisse a nunc ac lectus faucibus porttitor. Suspendisse condimentum iaculis lacinia. Vivamus interdum dictum rhoncus. Cras lacinia quam non est dignissim consectetur. Praesent eu purus vel tortor aliquet dictum sed ut leo. Integer accumsan quam ipsum, in scelerisque elit ultrices a. Maecenas vel molestie risus.",
                            DatePosted = new DateTime(2019, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "7 Facts About Telerik UI Everyone Thinks are True"
                        },
                        new
                        {
                            PostId = 14,
                            BlogId = 3,
                            Content = "Nam tincidunt dignissim elementum. Suspendisse condimentum nulla ut lectus pretium pharetra quis eget justo. In condimentum justo ac varius rutrum. Praesent et suscipit velit, non efficitur mauris. Donec cursus lorem eu dui sollicitudin, pharetra tristique massa accumsan. Curabitur et malesuada tellus. Fusce ac elementum elit, a condimentum eros.",
                            DatePosted = new DateTime(2019, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "18 Podcasts About Telerik UI"
                        },
                        new
                        {
                            PostId = 15,
                            BlogId = 3,
                            Content = "Fusce consectetur cursus scelerisque. Mauris vestibulum aliquet gravida. Pellentesque vitae elit lectus. Suspendisse tempor aliquam risus, nec faucibus massa tincidunt ut. Vestibulum dapibus ligula sollicitudin odio interdum placerat. Curabitur tempus malesuada mi, a dignissim quam suscipit et. Nunc eget ultricies tellus, sit amet ultrices libero. Donec sollicitudin porta viverra. Mauris ac ligula sit amet dolor tincidunt hendrerit in vitae nibh. Mauris non mi purus. Fusce non convallis est. Fusce ipsum justo, malesuada mollis tortor a, scelerisque iaculis justo.",
                            DatePosted = new DateTime(2019, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Why Telerik UI Will Change Your Life"
                        });
                });

            modelBuilder.Entity("SampleServerSide.Post", b =>
                {
                    b.HasOne("SampleServerSide.Blog", "Blog")
                        .WithMany("Posts")
                        .HasForeignKey("BlogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
